version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Maps port 80 in the container to port 3000 on the host
    environment:
      - REACT_APP_API_URL=http://backend:3001/api  # Connect frontend to backend
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # Maps port 3001 in the container to port 3001 on the host
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/todos  # Connect backend to MongoDB
    networks:
      - app-network
  mongo:
    image: mongo
    ports:
      - "27017:27017"  # Maps port 27017 in the container to port 27017 on the host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge     # create a bridge network for the app