# resources that provide stable endpoints for accessing your applications within the cluster.
#"kubectl get services -n app-namespace"
#kubectl apply -f service.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-namespace
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-namespace
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: app-namespace
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo